version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: final-project-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/sql:/docker-entrypoint-initdb.d
    networks:
      - pg-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=testdatabase
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: final-project-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pg-network

volumes:
  postgres_data:

networks:
  pg-network:
